### ISSUE TITLE
Translate /help pages [French]

### ISSUE THREAD

**Issue by garethrees** [mysociety/sobanukirwa-theme#29]
Create the file with the locale prefix in the filename:

```
about.html.erb
about.fr.html.erb
```

**Comment by garethrees** [comment]
@StephenAbbott I can see you've now got a French alternative for each help page in https://github.com/Sobanukirwa/sobanukirwa-theme/tree/master/lib/views/help. Do you want me to pull these across?

**Comment by StephenAbbott** [comment]
Hi @garethrees. The French /help page translations aren't all complete yet. Claude is working on these as we speak and is currently about 80% done. Once those are complete, we will add a comment here. Apologies for confusion. I thought it would be useful to have this issue ahead of time so that we could plan it for future sprints

**Comment by garethrees** [comment]
Yep no problem – definitely good to get a heads up.

**Comment by Mikaclo** [comment]
The translation of help pages in French is finished.

**Comment by garethrees** [comment]
https://github.com/Sobanukirwa/sobanukirwa-theme/tree/master/lib/views/help

**Comment by garethrees** [comment]
Fixed in c03d0d5789f65644699c0abc6233c740a800e2ed

**Comment by garethrees** [comment]
Done: https://sobanukirwa.rw/fr/help/about
